name: S3 Upload

on:
  push:
    branches: main

permissions:
  id-token: write   # This is the "magic" line for OIDC
  contents: read

jobs:
  s3-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::347273193329:role/MaitreyaRole_GithubS3FilesSync
          aws-region: eu-central-1

      - name: Copy files to S3
        run: |
          aws s3 sync . s3://github-private-files --exclude ".git/*" --exclude ".github/*"